export const EnvAuthScopeEnum = {
    PROJECT: 'PROJECT',
    PROJECT_GROUP: 'PROJECT_GROUP',
} as const;
export type EnvAuthScopeEnumType = typeof EnvAuthScopeEnum[keyof typeof EnvAuthScopeEnum];
export const EnvAuthTypeEnum = {
    GLOBAL: 'GLOBAL',
    ENVIRONMENT: 'ENVIRONMENT',
    ENVIRONMENT_PARAM: 'ENVIRONMENT_PARAM',
    ENVIRONMENT_GROUP: 'ENVIRONMENT_GROUP',
} as const;

export const EnvTabTypeEnum = {
    ENVIRONMENT_PARAM: 'ENVIRONMENT_PARAM',
    ENVIRONMENT_HTTP: 'ENVIRONMENT_HTTP',
    ENVIRONMENT_DATABASE: 'ENVIRONMENT_DATABASE',
    ENVIRONMENT_HOST: 'ENVIRONMENT_HOST',
    ENVIRONMENT_PRE: 'ENVIRONMENT_PRE',
    ENVIRONMENT_POST: 'ENVIRONMENT_POST',
    ENVIRONMENT_ASSERT: 'ENVIRONMENT_ASSERT',
    ENVIRONMENT_SETTING: 'ENVIRONMENT_SETTING',
    ENVIRONMENT_FTP: 'ENVIRONMENT_FTP',
} as const;